### PR TITLE
DIS-1647 - Reorganize

### PR DESCRIPTION
**Pull request by dbirks**
- Moved all typescript-related config to an overrides block that applies just to typescript files.
- Removed some typescript rules from a section applying to `*.js` in the react.js config.
- Moved some almost identical config from node.js and react.js to common.js. One thing this does change is standardize on `ecmaVersion: 2019`, which is a change from `2017` that node.js originally had.

Opening draft PRs that consume this beta package, as I make them:
- https://github.com/polarislabs/aurora-client/pull/293
- https://github.com/polarislabs/horizon-pro-api/pull/490
- https://github.com/polarislabs/polaris-ui-reference/pull/75

Before merging:
- [ ] Bump version to a stable 2.2.0

### CODE REVIEW

**Review by khgriffi259 — APPROVED** [review]
LGTM

**Review by ronwarner1231 — DISMISSED** [review]
Looks good from my perspective!

**Comment by dbirks** [comment]
Thanks! I'll get this 2.2.0 version published, and then finish out this ticket by bumping all of the repos to use it.

**Review by ronwarner1231 — APPROVED** [review]

**Review by khgriffi259 — APPROVED** [review]
LGTM!

**Pull request merged**
