### PR TITLE
HPAPI-10 Publish to NPM as well

### PR DESCRIPTION
**Pull request by dbirks**
Publishing to both NPM and Github Packages now.
Bumped the version as well.

### CODE REVIEW

**Review by brettdavis4 — DISMISSED** [review]
This looks good to me.

**Review by jeffbum — APPROVED** [review]
LGTM

**Comment by dbirks** [comment]
Thanks guys! Merging...

**Comment by dbirks** [comment]
Oh good, the Actions were finally successful
https://github.com/polarislabs/eslint-config-polaris/actions/runs/483128892

**Pull request merged**
