### PR TITLE
Move Github Actions to all one job

### PR DESCRIPTION
**Pull request by dbirks**
Move Github Actions to all be in one job, so they share the filesystem.

Fixes error:
```
npm ERR! enoent ENOENT: no such file or directory, open 'package.json'
```

### CODE REVIEW

**Review by jeffbum — DISMISSED** [review]
LGTM

**Review by jeffbum — COMMENTED** [review]
You will need to change the version # right?

**Comment by dbirks** [comment]
Oh yes you're right, I forgot to do that last time too.

**Review by jeffbum — APPROVED** [review]
LGTM

**Pull request merged**
